version: "3.9"
services:
  webserver:
    image: "caddy:2-alpine"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "$PWD/html:/var/www/html"
      - "$PWD/Caddyfile:/etc/caddy/Caddyfile"
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - cgi
      - db
  cgi:
    build:
      context: "backend"
      dockerfile: "phpWithPgsql.Dockerfile"
    volumes:
      - "$PWD/html:/var/www/html"
    depends_on:
      - db
  db:
    image: "postgres:17-alpine"
    environment:
      POSTGRES_PASSWORD: "postgres"
  adminer:
    image: adminer
    ports:
      - "8888:8080"
    depends_on:
      - db
volumes:
  caddy_data:
  caddy_config:
